{% set version = "0.2.0" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-rvcheck
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/rvcheck_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/rvcheck/rvcheck_{{ version }}.tar.gz
  sha256: eacefdf6e8c3e55a50657f6a34d7b1b7be3b18451fad850326700b847012fd25

build:
  merge_build_host: true  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-biocmanager
    - r-rlang
  run:
    - r-base
    - r-biocmanager
    - r-rlang

test:
  commands:
    - $R -e "library('rvcheck')"           # [not win]
    - "\"%R%\" -e \"library('rvcheck')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=rvcheck
  license: Artistic-2.0
  summary: Check latest release version of R and R package (both in 'CRAN', 'Bioconductor' or 'Github').
  license_family: OTHER
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/Artistic-2.0

extra:
  recipe-maintainers:
    - conda-forge/r
    - rvalieris

# Package: rvcheck
# Type: Package
# Title: R/Package Version Check
# Version: 0.1.6
# Authors@R: c(person(given = "Guangchuang", family = "Yu", email = "guangchuangyu@gmail.com", role  = c("aut", "cre")), person(given = "Chun-hui", family = "Gao", email = "gaospecial@gmail.com", role = "ctb") )
# Maintainer: Guangchuang Yu <guangchuangyu@gmail.com>
# Description: Check latest release version of R and R package (both in 'CRAN', 'Bioconductor' or 'Github').
# Depends: R (>= 3.4.0)
# Imports: BiocManager, utils, rlang
# License: Artistic-2.0
# Encoding: UTF-8
# LazyData: true
# RoxygenNote: 6.1.1
# NeedsCompilation: no
# Packaged: 2019-10-31 02:50:23 UTC; ygc
# Author: Guangchuang Yu [aut, cre], Chun-hui Gao [ctb]
# Repository: CRAN
# Date/Publication: 2019-10-31 06:20:03 UTC
