{% set version = "0.1.5" %}

package:
  name: r-rvcheck
  version: {{ version|replace("-", "_") }}

source:
  fn: rvcheck_{{ version }}.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/rvcheck_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/rvcheck/rvcheck_{{ version }}.tar.gz
  sha256: 4edd921c2261e5a05c191cdffa23366965e852ba06205c9aaa00d3a707164294

build:
  noarch: generic
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - r-base
    - r-rlang
    - r-biocmanager
  run:
    - r-base
    - r-rlang
    - r-biocmanager

test:
  commands:
    - $R -e "library('rvcheck')"  # [not win]
    - "\"%R%\" -e \"library('rvcheck')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=rvcheck
  license: Artistic-2.0
  summary: Check latest release version of R and R package (both in 'CRAN', 'Bioconductor' or
    'Github').

extra:
  recipe-maintainers:
    - conda-forge/r
    - rvalieris
