appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: iRZftoD50cdG01G9zUttRtfp1Ewu+ZHANi808fclcoOrBavT4/zwJnikxRQEuBAqvfIyvCPYOwaQDHYF6robajLWZv6Dkh9LhWeO82tXQailP8KpCf5NkWun/JOCo5dXR790/2iUi3yAjcplvFZank6aWARlADcpyWjTwX+5Ty407+33ZCnY6rphZ3sXKEvhU3MXr4KFvtV+/jZoexhrz9KytU/TE3q00o0HugHeCEwnYxCi17gcq/QOn0zMw0AmlyoXeNFNWC2Gi/xLDvpyaaJdzjLnQ+XeasbRnJwqZiozOu/uZEwjJUv6NJmC9ZzMiS5I+tEAye8q1CSfvIkPevDAqcZuwegfeir5tQ0SGSQpFfFN7Q86nphfRPEbW7Mudorm5o6sHbp8icjOTjKxQBz+cx1odEp/8BEGlighiEL0WB0tD8tWqjxeL78aY66YzHvSC5RuOgblB9q8t/busdCgOqVXpTcm2grJ7ALfs12U5fARdDJxVxrO053ZvTCb2s9hptyLOLjYiZMyGYzZTWFIIwIF//4s4U+incbEodJSYj81oVZ4fmLovScWtoG+JTSizNj6RFPBo1pMF/1M4cf4bNysvVp7F5E8Svt5CI/hGs5UER+SRzDcmxoJtlTAKCt2NwQXJfAD/TGXynJO3bpMyenOzGK+PVQ5SZJVrvQ=
conda_forge_output_validation: false
