travis:
  secure:
    BINSTAR_TOKEN: DiaFWQWJdWFU3yqATznNauTdmWCuGBNO4XxM8XS6eHdNQZKmzHLQS1bD/v+1KVUjUgU8Cxb/L7DhEv/ykQmTantFRTswIdIydLvBGNY3TNljPhGRqXRLUjgYO9z6Tq5JyfLd56aJKogPBfIjjHNuQ7x4vCFIs8kKq6dat7VE+qxe1f5W7OyylQ+y7J25ybj2fVEX6Xty7H0qGt3J+DJn2FY0z3vPXTKHc7EuRz/xY0bteKJU8RKDrucOxmGttltWW6OeJQI+Ma7tgpSg+t04RvIx6ZbMIo6sqfZghRLIosWYxIEgUDEmEhQnSw6qfgcOqxS5zyrNuxzvNHGh3eJumYToAEA8I1hAyzhi2+nFcObL1GcvlQka+rocqfxUbAXsupdYCgAscPAfNv6sENhxAsA2/v4J0YmTqA2t7KWxzKabRY8VV3UshuigCgo1pcI0+sZ8LcN15RMmy4VG64TXv7tRw6VViaAEMIlPzW+dTUKazuZ68x9pNbtAs3t4kIGrhs5ZXRRMsC8TLvto8RgPLWb0tmZLJpw7dc7E03K7G32UheYUJTwR6VG6UcAzVElhp8rCOOEsFBuwjHV6g42turqP9o6d2isZMvHL+Ss2te3IIvICsSba1ZTbAT0Rr/yeR9+7sQ0f4o7gK14JVXBr6JzXCQVDWX+A1ZCVaIC91qg=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
